keys:
  - &admin_leix age1wtzrvpnqc806yzvhkx9lfapnm6ck65p76j5u47u9p87ynq0hze7smwsume
  - &server_kuro age1svwxndx8uue2n0jkxgnsdjcqa9c4x6vujqygufrkxn28f27dxekqy4qqfg
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *admin_leix
